AC_DEFUN([AC_CC_D_FORTIFY_SOURCE],[
      OLD_CFLAGS="$CFLAGS"
      OLD_CXXFLAGS="$CXXFLAGS"
      CFLAGS="-Wall -W -Werror $CFLAGS"
      CXXFLAGS="-Wall -W -Werror $CXXFLAGS"
      gl_COMPILER_OPTION_IF([-D_FORTIFY_SOURCE=2], [
        CFLAGS="$OLD_CFLAGS -D_FORTIFY_SOURCE=2"
        CXXFLAGS="$OLD_CXXFLAGS -D_FORTIFY_SOURCE=2"
      ], [CFLAGS="$OLD_CFLAGS"
CXXFLAGS="$OLD_CXXFLAGS"], [AC_LANG_PROGRAM([[#include <stdio.h>]],[])])
]) 
